# Generated by Django 4.1.7 on 2023-02-20 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sneakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название кроссовки')),
                ('color', models.CharField(max_length=30, verbose_name='Цвет')),
                ('size', models.CharField(max_length=30, verbose_name='Размер кросовки')),
                ('price', models.DecimalField(decimal_places=12, max_digits=30)),
                ('in_stock', models.BooleanField(verbose_name='В наличии')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Brand', to='brand.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='category.category')),
            ],
        ),
        migrations.CreateModel(
            name='SneakersImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_images')),
                ('sneaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Images', to='sneakers.sneakers')),
            ],
        ),
    ]
