# Generated by Django 4.1.7 on 2023-02-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakers',
            name='size',
            field=models.BigIntegerField(verbose_name='Размер кросовки'),
        ),
    ]
