# Generated by Django 4.1.7 on 2023-02-25 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sneakers',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='sneakers',
            name='color',
        ),
        migrations.RemoveField(
            model_name='sneakers',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='sneakers',
            name='size',
        ),
    ]
