# Generated by Django 4.1.7 on 2023-02-22 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0003_alter_sneakers_brand_alter_sneakers_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sneakersimage',
            old_name='sneaker',
            new_name='sneakers',
        ),
    ]
