# Generated by Django 4.1.7 on 2023-02-22 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0004_rename_sneaker_sneakersimage_sneakers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('Sneakers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sneakers.sneakers')),
            ],
        ),
    ]
